version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-name: "discord.js"
        dependency-type: "direct"
      - dependency-name: "discord.js-selfbot-v13"
        dependency-type: "direct"
      - dependency-name: "grammy"
        dependency-type: "direct"
      - dependency-name: "@grammyjs/auto-retry"
        dependency-type: "direct"
